name: NPM Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Publish package
        run: npm publish 
        with:
          npm_token: ${{ secrets.TOKEN }}
